### PR TITLE
feat: include the purity analysis into the 'run_api` command

### LINKED ISSUE #239: Include the purity analysis into the `run_api` command
### Is your feature request related to a problem?

Right now, the purity analysis is not run when a API is analyzed.

### Desired solution

Run the purity analysis and return a json file with the results. 

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by lukarade**
Closes #239 

### Summary of Changes

The newly added purity analysis entry function: `get_purity_result` is now called when the `run_api` command is executed.
It is the starting point of the purity analysis and runs it on the provided `src_path` string, representing the package to analyze.

This includes further improvements and bug fixes to the purity analysis itself.

### CODE REVIEW

**Comment by lukarade** [comment]
This PR is ready for review, except for the one failed test due to a recursion bug I cannot fix. It would be great if you could take a look at it @lars-reimann.

**Comment by lukarade** [comment]
@lars-reimann the fix we found lead to some other tests failing. I will fix this, but it will take a while.

> This PR is ready for review, except for the one failed test due to a recursion bug I cannot fix. It would be great if you could take a look at it @lars-reimann.
> 
> I tried to change the `__hash__` methods to no longer use `str()`, which solved the problem by using only the attributes with primitive datatypes for hashing. On the other hand, this simple hashing approach led to different objects being equal. When using attributes with a non-primitive data types to fix this, the RecursionError occurred again.

**Comment by lars-reimann** [comment]
> @lars-reimann the fix we found lead to some other tests failing. I will fix this, but it will take a while.

No worries and good luck with that.

**Review by lars-reimann — APPROVED** [review]
I've only had time for spot checks, but in that context everything looks great. Thank you!

**Pull request merged**
